#!/usr/bin/env bash
#
# MUFF-39 — deploy the MCP server to AWS Lambda. Idempotent: safe to re-run;
# creates resources only if missing, otherwise updates code + config.
#
#   bundle (esbuild) → zip → Secrets Manager seed → IAM role → Lambda → API Gateway (HTTP API)
#
# Why plain CLI instead of CDK/SAM/Terraform: four resources, one function,
# a personal account. The ticket says "pick simplest" — this is it, and every
# AWS call is visible instead of hidden behind a synthesizer. Graduate to IaC
# when there's a second environment or a second person.
#
# Teardown (undo everything this script creates):
#   aws apigatewayv2 delete-api --api-id $(aws apigatewayv2 get-apis --region us-east-2 --query "Items[?Name=='muff-mcp-api'].ApiId | [0]" --output text) --region us-east-2
#   aws lambda delete-function --function-name muff-mcp-server --region us-east-2
#   aws iam delete-role-policy --role-name muff-mcp-lambda-role --policy-name muff-mcp-permissions
#   aws iam delete-role --role-name muff-mcp-lambda-role
#   aws secretsmanager delete-secret --secret-id muff/yahoo-tokens --region us-east-2

set -euo pipefail
cd "$(dirname "$0")/.."

REGION="${AWS_REGION:-us-east-2}"
FUNC="muff-mcp-server"
ROLE="muff-mcp-lambda-role"
POLICY_NAME="muff-mcp-permissions"
SECRET="muff/yahoo-tokens"
BUNDLE_DIR="dist/lambda"

get_env() { grep -E "^$1=" .env 2>/dev/null | head -1 | cut -d= -f2- || true; }

[[ -f .env ]] || { echo "❌ No .env — copy .env.example and fill in Yahoo creds."; exit 1; }
YAHOO_CLIENT_ID="$(get_env YAHOO_CLIENT_ID)"
YAHOO_CLIENT_SECRET="$(get_env YAHOO_CLIENT_SECRET)"
[[ -n "$YAHOO_CLIENT_ID" && -n "$YAHOO_CLIENT_SECRET" ]] || {
  echo "❌ YAHOO_CLIENT_ID / YAHOO_CLIENT_SECRET missing from .env"; exit 1; }

# Stable per-deployment bearer token; generated once and kept in .env.
MCP_AUTH_TOKEN="$(get_env MCP_AUTH_TOKEN)"
if [[ -z "$MCP_AUTH_TOKEN" ]]; then
  MCP_AUTH_TOKEN="$(openssl rand -hex 32)"
  printf '\n# Bearer token the deployed MCP server requires (generated by infra/deploy.sh)\nMCP_AUTH_TOKEN=%s\n' "$MCP_AUTH_TOKEN" >> .env
  echo "==> Generated MCP_AUTH_TOKEN → .env"
fi

echo "==> Bundling src/mcp/lambda.ts"
npx esbuild src/mcp/lambda.ts --bundle --platform=node --format=esm --target=node22 \
  --outfile="$BUNDLE_DIR/index.mjs" \
  --banner:js='import { createRequire } from "node:module"; const require = createRequire(import.meta.url);' \
  --log-level=warning
(cd "$BUNDLE_DIR" && rm -f function.zip && zip -q function.zip index.mjs)
echo "    $(du -h "$BUNDLE_DIR/function.zip" | cut -f1) zipped"

# --- Secrets Manager: seed once, never overwrite -----------------------------
# After first deploy the LAMBDA owns the secret (it writes refreshed tokens
# back), so a redeploy must not clobber it with a stale local .tokens.json.
if aws secretsmanager describe-secret --secret-id "$SECRET" --region "$REGION" >/dev/null 2>&1; then
  echo "==> Secret $SECRET exists — leaving it alone (Lambda may hold fresher tokens)"
else
  [[ -f .tokens.json ]] || { echo "❌ No .tokens.json — run 'npm run auth' first."; exit 1; }
  echo "==> Creating secret $SECRET from .tokens.json"
  aws secretsmanager create-secret --name "$SECRET" \
    --description "MUFF.ai Yahoo OAuth token set (access + refresh); the Lambda refreshes it in place" \
    --secret-string file://.tokens.json --region "$REGION" >/dev/null
fi
SECRET_ARN="$(aws secretsmanager describe-secret --secret-id "$SECRET" --region "$REGION" --query ARN --output text)"

# --- IAM: execution role, least privilege ------------------------------------
NEW_ROLE=0
if ! aws iam get-role --role-name "$ROLE" >/dev/null 2>&1; then
  echo "==> Creating role $ROLE"
  aws iam create-role --role-name "$ROLE" \
    --description "MUFF.ai MCP server Lambda execution role" \
    --assume-role-policy-document '{
      "Version": "2012-10-17",
      "Statement": [{"Effect": "Allow", "Principal": {"Service": "lambda.amazonaws.com"}, "Action": "sts:AssumeRole"}]
    }' >/dev/null
  NEW_ROLE=1
fi
# Logs + read/write exactly one secret. PutSecretValue matters: token refresh
# writes back, so this is not a read-only consumer.
aws iam put-role-policy --role-name "$ROLE" --policy-name "$POLICY_NAME" \
  --policy-document '{
    "Version": "2012-10-17",
    "Statement": [
      {"Effect": "Allow",
       "Action": ["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents"],
       "Resource": "arn:aws:logs:*:*:*"},
      {"Effect": "Allow",
       "Action": ["secretsmanager:GetSecretValue", "secretsmanager:PutSecretValue"],
       "Resource": "'"$SECRET_ARN"'"}
    ]
  }'
ROLE_ARN="$(aws iam get-role --role-name "$ROLE" --query Role.Arn --output text)"
if [[ "$NEW_ROLE" == 1 ]]; then
  echo "    waiting 10s for IAM propagation (new roles aren't instantly assumable)"
  sleep 10
fi

# --- Lambda ------------------------------------------------------------------
# Env JSON built by node so special characters in secrets can't break quoting.
ENV_JSON="$(TOKENS_SECRET_ID="$SECRET" YAHOO_CLIENT_ID="$YAHOO_CLIENT_ID" \
  YAHOO_CLIENT_SECRET="$YAHOO_CLIENT_SECRET" MCP_AUTH_TOKEN="$MCP_AUTH_TOKEN" \
  node -e 'const p = ["TOKENS_SECRET_ID","YAHOO_CLIENT_ID","YAHOO_CLIENT_SECRET","MCP_AUTH_TOKEN"];
    console.log(JSON.stringify({Variables: Object.fromEntries(p.map(k => [k, process.env[k]]))}))')"

if aws lambda get-function --function-name "$FUNC" --region "$REGION" >/dev/null 2>&1; then
  echo "==> Updating $FUNC (code, then config)"
  aws lambda update-function-code --function-name "$FUNC" \
    --zip-file "fileb://$BUNDLE_DIR/function.zip" --region "$REGION" >/dev/null
  aws lambda wait function-updated --function-name "$FUNC" --region "$REGION"
  aws lambda update-function-configuration --function-name "$FUNC" \
    --environment "$ENV_JSON" --region "$REGION" >/dev/null
  aws lambda wait function-updated --function-name "$FUNC" --region "$REGION"
else
  echo "==> Creating $FUNC"
  aws lambda create-function --function-name "$FUNC" \
    --description "MUFF.ai Yahoo Fantasy MCP server (Streamable HTTP, stateless)" \
    --runtime nodejs22.x --handler index.handler \
    --role "$ROLE_ARN" \
    --zip-file "fileb://$BUNDLE_DIR/function.zip" \
    --timeout 30 --memory-size 512 \
    --environment "$ENV_JSON" --region "$REGION" >/dev/null
  aws lambda wait function-active --function-name "$FUNC" --region "$REGION"
fi

# --- API Gateway (HTTP API) --------------------------------------------------
# Public front door. We tried the simpler Function URL first, but this account
# denies anonymous function-URL invokes even with the textbook resource policy
# (AccessDeniedException before the function is reached). An HTTP API with a
# $default → Lambda proxy route is unambiguous about public access, and its
# payload (v2.0) is the same event shape, so the handler doesn't care which
# front door invoked it. Auth stays at the app layer (bearer token).
API_NAME="muff-mcp-api"
API_ID="$(aws apigatewayv2 get-apis --region "$REGION" \
  --query "Items[?Name=='$API_NAME'].ApiId | [0]" --output text)"
if [[ -z "$API_ID" || "$API_ID" == "None" ]]; then
  echo "==> Creating HTTP API $API_NAME"
  FUNC_ARN="$(aws lambda get-function --function-name "$FUNC" --region "$REGION" \
    --query Configuration.FunctionArn --output text)"
  # --target = "quick create": $default stage (auto-deploy) + proxy route in one call.
  API_ID="$(aws apigatewayv2 create-api --name "$API_NAME" --protocol-type HTTP \
    --target "$FUNC_ARN" --region "$REGION" --query ApiId --output text)"
  ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
  aws lambda add-permission --function-name "$FUNC" \
    --statement-id ApiGatewayInvoke \
    --action lambda:InvokeFunction --principal apigateway.amazonaws.com \
    --source-arn "arn:aws:execute-api:$REGION:$ACCOUNT_ID:$API_ID/*" \
    --region "$REGION" >/dev/null
fi
URL="https://$API_ID.execute-api.$REGION.amazonaws.com/"

# Record the URL for verify:remote.
CURRENT_URL="$(get_env MCP_URL)"
if [[ -z "$CURRENT_URL" ]]; then
  printf '\n# Deployed MCP endpoint (written by infra/deploy.sh)\nMCP_URL=%s\n' "$URL" >> .env
elif [[ "$CURRENT_URL" != "$URL" ]]; then
  sed -i '' "s|^MCP_URL=.*|MCP_URL=$URL|" .env
fi

echo
echo "✅ Deployed: $URL"
echo "   Smoke test:  npm run verify:remote"
