/**
 * MUFF-38 — render the structured digest to chat text.
 *
 * Deterministic: layout lives in code, not in the model. *bold* renders in
 * BOTH Telegram (Markdown parse_mode) and WhatsApp, which is the whole
 * forwarding story — one format, two apps.
 */

import type { Digest } from "./generate.ts";
import type { WeekFacts } from "./facts.ts";

const medals = ["🥇", "🥈", "🥉"];

export function renderDigest(facts: WeekFacts, d: Digest): string {
  const lines: string[] = [
    `🏈 *MUFF WEEKLY — Week ${facts.week}* 🏈`,
    "",
    `_${d.headline}_`,
    "",
    d.recap,
    "",
    "*📋 Around the league*",
    ...d.game_notes.map((n) => `• ${n}`),
    "",
    "*🔥 Trash talk corner*",
    ...d.trash_talk.map((t) => `• ${t}`),
    "",
    "*👑 Power rankings*",
    ...d.power_rankings
      .sort((a, b) => a.rank - b.rank)
      .map((p) => `${medals[p.rank - 1] ?? `${p.rank}.`} *${p.team}* — ${p.comment}`),
  ];
  if (d.waiver_watch.trim()) {
    lines.push("", "*🛒 Waiver watch*", d.waiver_watch.trim());
  }
  lines.push("", `_Generated by MUFF.ai — argue with the data, not with me._`);
  return lines.join("\n");
}
