/**
 * MUFF-38 — render the structured digest to chat text.
 *
 * Deterministic: layout lives in code, not in the model. *bold* renders in
 * BOTH Telegram (Markdown parse_mode) and WhatsApp, which is the whole
 * forwarding story — one format, two apps.
 */

import type { Digest } from "./generate.ts";
import type { WeekFacts } from "./facts.ts";
import { teamKey } from "./team-names.ts";

const medals = ["🥇", "🥈", "🥉"];

/** ▲2 / ▼1 / — / 🆕, computed from last week's PUBLISHED rankings — never by the model. */
function movement(
  team: string,
  rank: number,
  prev: WeekFacts["previous_power_rankings"],
): string {
  if (!prev) return "";
  // Key comparison, not ===: week-1 history was written before team names were
  // canonicalised and carries the model's straight apostrophe.
  const was = prev.find((p) => teamKey(p.team) === teamKey(team))?.rank;
  if (was === undefined) return " 🆕";
  const delta = was - rank;
  if (delta > 0) return ` ▲${delta}`;
  if (delta < 0) return ` ▼${-delta}`;
  return " —";
}

export function renderDigest(facts: WeekFacts, d: Digest): string {
  const lines: string[] = [
    `🏈 *MUFF WEEKLY — Week ${facts.week}* 🏈`,
    "",
    `_${d.headline}_`,
    "",
    d.recap,
    "",
    "*👑 Power rankings*",
    ...d.power_rankings
      .sort((a, b) => a.rank - b.rank)
      .map(
        (p) =>
          `${medals[p.rank - 1] ?? `${p.rank}.`}${movement(p.team, p.rank, facts.previous_power_rankings)} *${p.team}* — ${p.comment}`,
      ),
  ];
  // MUFF-40: the poll itself is a separate Telegram message; this is the
  // deterministic tease above it. Layout, not prose, so no model involved.
  const game = facts.game_of_the_week;
  if (game && game.teams.length === 2) {
    const [a, b] = game.teams;
    lines.push(
      "",
      `*🎯 Game of the Week ${game.week}*`,
      `${a.team} (${a.record}) vs ${b.team} (${b.record}) — projected ${a.projected}–${b.projected}. Vote below 👇`,
    );
  }
  lines.push("", `_Generated by MUFF.ai — argue with the data, not with me._`);
  return lines.join("\n");
}
